project_id = "vbcsuoubxyhjhxcgrqco"

[functions.shovels-permits]
verify_jwt = true

[functions.admin-users]
verify_jwt = true

[functions.smarty-proxy]
verify_jwt = true

[functions.smarty-autocomplete]
verify_jwt = false

[functions.attom-property]
verify_jwt = true